name: CD chambeaya

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
    paths:
      - 'chambeajava/**'

jobs:
  
  deploy:
    name: Deploy examen and cache all java dependency
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
          
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: chambeajava-${{ hashFiles('**/pom.xml') }}
                      
      - name: package Project examen
        run: |
          sed -i 's/password_token/${{ secrets.GHCR_PAT }}/g' settings.xml
          mvn --settings settings.xml -f chambeajava/pom.xml deploy
          mvn --settings settings.xml -f chambeajava/pom.xml clean verify sonar:sonar -Dsonar.login=${{secrets.SNR_TKN}} -Dsonar.host.url=https://sonarcloud.io/ -Dsonar.organization=chambeaya -Dsonar.projectKey=kix-mx-chambeaya
          
      
          
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Packages
        uses: docker/login-action@v1
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GHCR_PAT }}

      - name: Build image and push to GitHub Container Registry
        uses: docker/build-push-action@v2
        with:
            # relative path to the place where source code with Dockerfile is located
            context: ./chambeajava/
            # Note: tags has to be all lower-case
            tags: |
              ghcr.io/kixzeit/dockerized-chambeajava:latest
            # build on feature branches, push only on main branch
            push: ${{ github.ref == 'refs/heads/main' }}
